export const FETCH_COLLABORATORS_REQUEST = 'FETCH_COLLABORATORS_REQUEST';
export const FETCH_COLLABORATORS_SUCCESS = 'FETCH_COLLABORATORS_SUCCESS';
export const FETCH_COLLABORATORS_ERROR = 'FETCH_COLLABORATORS_ERROR';
export const FETCH_COLLABORATORS_REQUEST_BY_PAGE = 'FETCH_COLLABORATORS_REQUEST_BY_PAGE';
export const FETCH_COLLABORATORS_REQUEST_BY_QUERY = 'FETCH_COLLABORATORS_REQUEST_BY_QUERY';