export const FETCH_POSTS_REQUEST = 'FETCH_POSTS_REQUEST';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_ERROR = 'FETCH_POSTS_ERROR';
export const FETCH_POSTS_REQUEST_BY_PAGE = 'FETCH_POSTS_REQUEST_BY_PAGE';

export const FETCH_POSTS_REQUEST_BY_QUERY = 'FETCH_POSTS_REQUEST_BY_QUERY';
export const FETCH_POSTS_REQUEST_BY_QUERY_AND_PAGE = 'FETCH_POSTS_REQUEST_BY_QUERY_AND_PAGE';

export const FETCH_PUBLISHED_POSTS_REQUEST = 'FETCH_PUBLISHED_POSTS_REQUEST';
export const FETCH_PUBLISHED_POSTS_REQUEST_BY_PAGE = 'FETCH_PUBLISHED_POSTS_REQUEST_BY_PAGE';

export const FETCH_DRAFT_POSTS_REQUEST = 'FETCH_DRAFT_POSTS_REQUEST';
export const FETCH_DRAFT_POSTS_REQUEST_BY_PAGE = 'FETCH_DRAFT_POSTS_REQUEST_BY_PAGE';

export const POST_STATUS_ALL = 'published';
export const POST_STATUS_PUBLISHED = 'published';
export const POST_STATUS_DRAFT = 'draft';