export const FETCH_TAGS_REQUEST = 'FETCH_TAGS_REQUEST';
export const FETCH_TAGS_SUCCESS = 'FETCH_TAGS_SUCCESS';
export const FETCH_TAGS_ERROR = 'FETCH_TAGS_ERROR';
export const FETCH_TAGS_REQUEST_BY_PAGE = 'FETCH_TAGS_REQUEST_BY_PAGE';
export const FETCH_TAGS_REQUEST_BY_QUERY = 'FETCH_TAGS_REQUEST_BY_QUERY';